# Generated by Django 3.2.16 on 2026-01-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-size',), 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name': 'Подкатегорию', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'size')},
        ),
    ]
